# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avc < Formula
  desc "Agentic Version Control — lightweight, agent-safe project snapshots"
  homepage "https://github.com/trevarix/agentic-vc"
  version "0.2.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_darwin_amd64.tar.gz"
      sha256 "ebf1f1e1cf5dae001a78479d108ccc2eb5cf069f49ef6627f14cba8166938d0e"

      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_darwin_arm64.tar.gz"
      sha256 "475687aebe87137ae98bb77d966d9ac0d1dd764151b9ba676b8b6b166b4dbd72"

      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_linux_amd64.tar.gz"
      sha256 "6fce23afaaf49df4e1264b61823316a4b316d3147ab036f66b3d75a8e5eff58a"
      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_linux_arm64.tar.gz"
      sha256 "d6eb963459e8a0435ccba240dae8d0d95a9698d082eebcd922d49df45260a64d"
      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  test do
    system "#{bin}/avc", "--version"
  end
end
