# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avc < Formula
  desc "Agentic Version Control — lightweight, agent-safe project snapshots"
  homepage "https://github.com/trevarix/agentic-vc"
  version "0.2.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_darwin_amd64.tar.gz"
      sha256 "de5f043fd7e882173514b63696c3b980152c8feac83f6a426be7d59f89c715b0"

      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_darwin_arm64.tar.gz"
      sha256 "f69c823ca8b6f9db76c2d0a1c38c18a1208dba8c261d1e392a39ae2f3429c54d"

      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_linux_amd64.tar.gz"
      sha256 "34a179dad2e2e9384ab39ad26511407f73ed0e1c9e7aa971fff3bf57275056f1"
      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.2.1/avc_0.2.1_linux_arm64.tar.gz"
      sha256 "895a54c44d027a4d97675513c6d9a878b24876b35215803f2b24098cea9b01e7"
      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  test do
    system "#{bin}/avc", "--version"
  end
end
