# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avc < Formula
  desc "Agentic Version Control — lightweight, agent-safe project snapshots"
  homepage "https://github.com/trevarix/agentic-vc"
  version "0.3.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.3.0/avc_0.3.0_darwin_amd64.tar.gz"
      sha256 "0f6f9a2efeefbda1c403e846c06ff7123033ca36e5bee3f6b379d2c7ea1d8659"

      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.3.0/avc_0.3.0_darwin_arm64.tar.gz"
      sha256 "04ed38772db4ca249d83139ada93c024f2bd61b2b86dc36466fc1ac2118cc552"

      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.3.0/avc_0.3.0_linux_amd64.tar.gz"
      sha256 "10acdab5b20607d823a32e0a22f2e0375f17fe40b7dcb343386552c4dbd72eab"
      define_method(:install) do
        bin.install "avc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trevarix/agentic-vc/releases/download/v0.3.0/avc_0.3.0_linux_arm64.tar.gz"
      sha256 "e8f170d072f6ca3d14487fc37e8f3254848cba220be42a8908de051c876fc937"
      define_method(:install) do
        bin.install "avc"
      end
    end
  end

  test do
    system "#{bin}/avc", "--version"
  end
end
